services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-battleships}
    ports:
      - "5433:5432" # containerised db available on localhost:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # check so that the db is ready before starting the backend
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-battleships}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mfendler/battleships-app:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-battleships}
      DB_HOST: db # hostname of the db in the container network == service name in docker-compose

volumes:
  postgres_data: